- src/components/Sections/Library/LibraryContainer.js
https://issues.kbb1.com/issue/AR-126
> Alphabetically sort chapters, except Shamati

- src/stylesheets/includes/_media-player.scss
> Bug fix: Player control panel disappears on IE

- src/components/AVPlayer/AVCenteredPlay.js
- src/components/AVPlayer/AVPlayer.js
- src/components/AVPlayer/AVSpinner.js
and break again the spinner and centered player to components
> Fix Video player forever stuck in "loading" (AR-180)

- src/components/Pages/Unit/widgets/UnitMaterials/Sources/Sources.js
resolve bug AR-193 by adding null check to if condition
> resolve bug AR-193

- src/components/Pages/Unit/widgets/UnitMaterials/Sketches.js
> multi image display bug fix

- src/components/AVPlayer/AVAudioVideo.js
set the popup direction to downward=false
> fix AR-137

- src/stylesheets/includes/_media-player.scss
AR-155 Timeline overlays volume bar
Seek with the time line (white bar) after the volume button
open the volume bar,
the volume bar should be on top the timeline...
> change volume bar z-index to 1

- src/components/Sections/Library/LibraryContainer.js
- src/components/Sections/Library/TOC.js
- src/helpers/utils.js
- src/index.js
- src/redux/modules/sources.js
Optimize rendering
Separate not-to-sort from not-to-filter
> AR-249 Library - shamati autocomplete with numbers

- src/components/Pages/Unit/widgets/UnitMaterials/Transcription/Transcription.js
the transcription is probably the largest text file of a language...
> changed transcription to select the largest file of a language

- src/components/Layout/Layout.js
- src/components/Layout/UILanguage.js
- src/helpers/url.js
- src/sagas/device.js
- it should depend on location
- it should use string to pass to Link (then it is appended as a prefix to current location)
> Preferred content language -- fix UILanguages:

- src/components/AVPlayer/AVPlayer.js
fix Player bar disappear sometimes by checking if the mouse position is in or out the player controls.
> fix Player bar disappear sometimes

- src/components/AVPlayer/AVPlayer.js
- src/components/AVPlayer/AVPlayerMobile.js
switched from url to item id when saving the current position in local storage
> AR-373 Player: can happen that two different times are stored

- src/components/AVPlayer/AVPlayer.js
- src/components/AVPlayer/AVPlayerMobile.js
AR-348 Share feature: "Start - Stop limits" do not disappear when you press play in the end of watching the slice.
> AR-348 Share feature: "Start - Stop limits" do not disappear

- src/components/AVPlayer/AVPlaybackRateMobile.js
- src/components/AVPlayer/AVPlayerMobile.js
> AR-391 Player - speed selection in mobile

- public/locales/de/common.json
- public/locales/en/common.json
- public/locales/es/common.json
- public/locales/he/common.json
- public/locales/ru/common.json
- public/locales/ua/common.json
- src/components/Sections/SimpleMode/Container.js
- src/components/Sections/SimpleMode/DesktopPage.js
- src/components/Sections/SimpleMode/MobilePage.js
- src/components/Sections/SimpleMode/RenderListHelpers.js
- src/components/Sections/SimpleMode/list.js
- src/redux/modules/simpelMode.js
- src/routesSSRData.js
- src/stylesheets/includes/_not-sorted-scss.scss
> Ar 398 new

- src/components/AVPlayer/AVPlayerMobile.js
AR-443 Shared link don't start on time on ios chrome
> AR-433 Shared link don't start on time on ios chrome

- src/components/Sections/Library/LibraryContainer.js
something currently fails with eslint on my comp
> AR-462 fixed bad source exception

- package-lock.json
- src/components/Sections/Topics/TopN.js
- src/stylesheets/includes/_not-sorted-scss.scss
- yarn.lock
> Ar 493 topic not found remove message

- src/components/Filters/components/CollectionsFilter.js
- src/components/Pages/UnitList/Page.js
- src/redux/modules/publications.js
- src/sagas/publications.js
> Ar 543 publication filters

- public/persons/baal-hasulam-es.html
- public/persons/michael-laitman-es.html
- public/persons/rabash-es.html
- server/app-dev.js
- yarn.lock
> Ar 573 spanish kabbalist pages

- src/components/Filters/components/Date/FastDayPicker.js
- src/components/Sections/SimpleMode/Container.js
- src/helpers/links.js
- Also add smooth behaviour to scroll to top when click on `change language` link
- Remove duplicate prop from fast day picker
> AR-593_add blog post type to canonical link

- src/routesSSRData.js
fixes
https://kabbalahmedia.info/en/lessons/daily/c/sVFN
(internal server error)
> fix for AR-434

- src/components/Layout/Layout.js
- src/components/Sections/Home/Container.js
- src/components/Sections/Lessons/MainPage.js
> Ar 639 search mobile

- src/components/AVPlayer/Share/BaseShareForm.js
- src/components/AVPlayer/Share/ShareFormDesktop.js
- src/helpers/url.js
> Ar 637 2 add aut start parameter to the share script

- src/components/Sections/Library/LibraryContainer.js
- src/components/Sections/Library/TOC.js
made some code improvements as well
> Ar 666 skip toc

- src/components/Filters/FiltersHydrator.js
- src/components/Pages/Unit/widgets/UnitMaterials/Sources/SourcesContainer.js
- yarn.lock
fixed the warning and also someone's left lint dependencies warning on SourceContainer
> Ar 693 filters warning

- server/renderer.js
- src/components/Language/LanguageSetter.js
- src/components/Layout/Layout.js
- src/components/Sections/Events/tabs/CollectionList/Container.js
- src/components/Sections/Home/LatestDailyLesson.js
- src/components/Sections/Library/LibraryContainer.js
- src/sagas/search.js
fixed some of them - you can merge meanwhile
> Ar 694 warning fix

- src/components/Sections/Events/tabs/CollectionList/Container.js
- src/components/Sections/Events/tabs/CollectionList/List.js
- src/redux/modules/filters.js
fixed loading empty results after filter
> Some more bugs

- src/components/Layout/Footer.js
- src/components/Sections/Library/LibraryContainer.js
- src/stylesheets/includes/_sources.scss
added some padding at the bottom of TOC for mobile
test on mobile!
> Ar 689 feedback button hides

- src/components/Pages/Unit/widgets/UnitMaterials/Transcription/Transcription.js
- src/components/Search/SearchResultCU.js
- src/components/Sections/Library/Library.js
- src/components/shared/TabsMenu.js
- src/helpers/links.js
- src/helpers/url.js
- src/stylesheets/includes/_not-sorted-scss.scss
@gshilin  task: Search result will redirect to exact place in the transcript
> Search result redirect to exact place in the transcript

- src/components/Pages/Unit/widgets/UnitMaterials/Transcription/Transcription.js
- src/components/Search/SearchResultBase.js
- src/components/Search/SearchResultCU.js
- src/components/Search/SearchResultSource.js
- src/components/Sections/Library/Library.js
- src/components/Sections/Library/LibraryContainer.js
Reverts Bnei-Baruch/kmedia-mdb#569
> Revert "Sources search result redirect to exact place"

- public/api/video/kmediaPlayerApi.js
- src/components/AVPlayer/AVPlayer.js
> Ar 710 control the embed player from on an external site

- src/components/Sections/Library/LibraryContainer.js
- src/helpers/__tests__/scrollToSearch.test.js
- src/helpers/utils.js
> Remove html tag from view on sorce

- src/components/Layout/DonateNow.js
- src/components/Layout/Layout.js
- src/components/Layout/MenuItems.js
- src/stylesheets/includes/_layout.scss
this is how we designed it with Yaakov Sabal
there is some mess in the code left by search team
> Virtual home button

- src/components/Sections/Home/Container.js
- src/components/Sections/Home/HomePage.js
- src/components/Sections/Home/LatestUpdate.js
- src/components/Sections/Home/LatestUpdatesSection.js
- src/helpers/links.js
- src/helpers/utils.js
- src/redux/modules/tags.js
front end ready, waiting for the backend changes
> Ar 719 latest updates

- public/locales/cs/common.json
- public/locales/de/common.json
- public/locales/en/common.json
- public/locales/es/common.json
- public/locales/he/common.json
- public/locales/it/common.json
- public/locales/ru/common.json
- public/locales/tr/common.json
- public/locales/ua/common.json
- src/components/Pages/PlaylistCollection/widgets/Playlist/Playlist.js
- src/components/Pages/PlaylistCollection/widgets/PlaylistAVBox/PlaylistAVBox.js
- src/components/Pages/Unit/Page.js
- src/components/Pages/Unit/widgets/Recommended/Main/Recommended.js
- src/components/Pages/Unit/widgets/Recommended/SameCollection/Container.js
- src/helpers/Api.js
- src/redux/index.js
- src/redux/modules/recommended.js
- src/sagas/index.js
- src/sagas/recommended.js
- src/stylesheets/includes/_video-player.scss
alex said its done
define in env:
REACT_APP_RECOMMENDED=https://kabbalahmedia.info/feed_api/recommend
> Ar 726 recommendations

- src/helpers/__tests__/search.test.js
- src/helpers/search.js
From trello: 
Autocompletion for Hagim: order years from New to Old
> order if written year as number more than 2000

- src/helpers/__tests__/search_bug_sourcesNotInTop.test.js
- src/helpers/search.js
task from trello 
At client: Show sources autocomplete results above other results
> order sorting priority

- public/locales/cs/common.json
- public/locales/de/common.json
- public/locales/en/common.json
- public/locales/es/common.json
- public/locales/he/common.json
- public/locales/it/common.json
- public/locales/ru/common.json
- public/locales/tr/common.json
- public/locales/ua/common.json
- src/components/Pages/PlaylistCollection/Page.js
- src/components/Pages/Unit/widgets/Recommended/Main/DisplayRecommended.js
- src/components/Pages/Unit/widgets/UnitMaterials/Materials.js
- src/components/shared/TabsMenu.js
- src/stylesheets/includes/_unit.scss
> Ar 740 tabs

- src/components/Pages/Collection/Container.js
- src/components/Pages/PlaylistCollection/Container.js
- src/components/Pages/PlaylistCollection/IdCheck.js
- src/components/Pages/PlaylistCollection/widgets/Playlist/Playlist.js
- src/components/Pages/PlaylistCollection/widgets/Playlist/PlaylistHeader.js
- src/components/Sections/Events/Collection.js
- src/components/Sections/Events/Unit.js
- src/components/Sections/Lessons/Collection/LastDaily.js
- src/components/Sections/Lessons/Collection/MainPage.js
- src/routes.js
> Ar 739 hook fix

- src/components/AVPlayer/AVPlayerMobile.js
- src/components/Pages/PlaylistCollection/widgets/Playlist/Playlist.js
Playlist Collection improved - IdCheck object created, unused files removed
> Ar 739 id check

- src/components/AVPlayer/AVPlaylistPlayer.js
- src/components/Pages/PlaylistCollection/Page.js
- src/components/Pages/PlaylistCollection/widgets/Playlist/Playlist.js
AVPlaylistPlayer changed to a function
> Av playlist change

- src/components/Pages/PlaylistCollection/Page.js
- src/components/Pages/Unit/Page.js
- src/components/Pages/Unit/widgets/AVBox/AVBox.js
- src/components/Sections/Publications/tabs/Articles/Unit.js
- src/stylesheets/includes/_video-player.scss
AR-749 was done here because i had to partially cancel previous changes
mainly removed unused css classes and simplified used objects was the solution!
and then had to do small css changes to fix a bit more
> Ar 745 mobile player fixes

- src/components/Layout/ContentLanguage.js
- src/components/Layout/HandleLanguages.js
- src/components/Layout/Layout.js
- src/components/Layout/UILanguage.js
> use History and Location hooks rather than passing values

- src/components/Layout/ContentLanguage.js
- src/components/Layout/HandleLanguages.js
- src/components/Layout/Layout.js
- src/components/Layout/UILanguage.js
more hooks to simplify the written
> Location hooks

- src/components/Filters/Filters.js
- src/components/Layout/UILanguage.js
- src/components/Sections/Events/tabs/CollectionList/Container.js
- src/components/Sections/Events/tabs/CollectionList/List.js
> fix collection loading on ui language change & performance

- src/components/AVPlayer/AVPlaylistPlayer.js
- src/components/Pages/PlaylistCollection/Page.js
- src/components/Pages/Unit/widgets/Recommended/Main/Recommended.js
> removed unneeded useCallbacks and more

- src/components/Search/SearchResultsContainer.js
- src/redux/modules/mdb.js
@gshilin 
- David, please change code to use ?. then if it provides an acceptable UI....
where?
> AR-767 Fix bug search result exception

- src/components/Pages/PlaylistCollection/Page.js
a small fix
don't erase the branch :)
> added a space between playlist and recommended

- src/components/Language/LanguageSetter.js
- src/components/Pages/PlaylistCollection/Page.js
- src/components/Pages/Unit/Page.js
- src/routes.js
fix unwanted language change to english
> Autoplay recommended

- src/components/AVPlayer/AVPlayer.js
- src/helpers/Api.js
- src/helpers/clientChronicles.js
- src/index.js
- src/redux/modules/chronicles.js
- src/redux/modules/player.js
- src/redux/modules/recommended.js
- src/sagas/recommended.js
https://issues.kbb1.com/issue/AR-769
Backend already deployed so you are good to go if everything is okay.
> AR-769: Add play and inactive actions. Store played units and don't recommend them.

- src/components/AVPlayer/AVPlayer.js
- src/components/Pages/Unit/widgets/Recommended/Main/DisplayRecommended.js
- src/components/Pages/Unit/widgets/Recommended/Main/Recommended.js
- src/helpers/Api.js
- src/helpers/clientChronicles.js
- src/index.js
- src/redux/createStore.js
- src/sagas/recommended.js
Reverts Bnei-Baruch/kmedia-mdb#697
> Revert "Fix player-stop event. Add recommend events via store actions."

- src/components/AVPlayer/AVPlayer.js
- src/components/App/App.js
- src/components/Pages/Unit/widgets/AVBox/AVBox.js
- src/components/Pages/Unit/widgets/Recommended/Main/DisplayRecommended.js
- src/components/Pages/Unit/widgets/Recommended/Main/Recommended.js
- src/components/Pages/Unit/widgets/Recommended/Main/UseRecommendedUnits.js
- src/helpers/Api.js
- src/helpers/clientChronicles.js
- src/redux/index.js
- src/redux/modules/chronicles.js
- src/sagas/recommended.js
This reverts commit f4d0f472929e2a5ac457e467af8d395aaf171c66.
> Fix player-stop event. Add recommend events via store actions.

- src/components/Layout/MenuItems.js
- src/components/Pages/Unit/widgets/Info/Info.js
> Some small fixes

- src/components/Sections/Lessons/tabs/Series/Container.js
- src/redux/modules/lessons.js
- src/stylesheets/includes/_topics.scss
> series-fixes

- .eslintrc
- .gitignore
- package.json
- src/components/Pages/UnitList/Page.js
see maybe we don't need that .prepush.eslintrc.json file anymore...
> Eslint files fix

- package.json
- src/components/AVPlayer/AVCenteredPlay.js
- src/components/AVPlayer/AVPlayer.js
- src/components/AVPlayer/AVPlayerMobile.js
- src/components/AVPlayer/AVPlaylistPlayer.js
- src/components/Filters/Filters.js
- src/components/Language/Selector/DropdownLanguageSelector.js
- src/components/Layout/Layout.js
- src/components/Pages/PlaylistCollection/Page.js
- src/components/Pages/PlaylistCollection/widgets/PlaylistAVBox/PlaylistAVBox.js
- src/components/Pages/Unit/Page.js
- src/components/Pages/Unit/widgets/AVBox/AVBox.js
- src/components/Pages/Unit/widgets/UnitMaterials/Sources/Sources.js
- src/components/Pagination/Pagination.js
- src/components/Sections/Library/Kabbalist.js
- src/components/Sections/Library/LibraryContainer.js
- src/components/Sections/Library/TOC.js
replaced classnames everywhere
can we remove classnames pkg?
> add clsx pkg

- src/components/Sections/SimpleMode/Container.js
- src/components/Sections/SimpleMode/Page.js
- src/components/Sections/SimpleMode/list.js
- src/sagas/simpleMode.js
converted SimpleModeContainer & some improvements
> More converts - SimpleModeContainer

- src/components/Sections/SimpleMode/list.js
> more-converts

- src/components/Search/SearchResultBase.js
- src/components/Search/SearchResults.js
fixed weird search results display bug
> funcky-grid-column

- .eslintrc
- src/components/AVPlayer/AVLanguage.js
- src/components/AVPlayer/AVSpinner.js
- src/components/Language/Selector/MenuLanguageSelector.js
- src/components/Pages/Unit/widgets/Downloads/MediaDownloads.js
- src/components/Pages/Unit/widgets/UnitMaterials/Sources/Sources.js
- src/components/Pages/Unit/widgets/UnitMaterials/Transcription/Transcription.js
- src/components/Sections/Library/Library.js
- src/components/Sections/Programs/tabs/Programs/List.js
- src/components/Sections/Publications/tabs/Twitter/Feed.js
- src/components/Sections/SimpleMode/RenderListHelpers.js
- src/components/shared/WipErr/WipErr.js
- src/helpers/language.js
> added splash wrappers

- src/components/Sections/Likutim/Likut.js
- src/components/Sections/Likutim/Main.js
- src/stylesheets/includes/_topics.scss
> All Likutim changes

- public/api/video/kmediaPlayerApi.js
- server/app-dev.js
- server/index.js
- server/kmedia.js
- server/middleware.js
- server/renderer.js
- src/components/Filters/Filters.js
this is instead of https://github.com/Bnei-Baruch/kmedia-mdb/pull/759
> Server-linting-new

- src/components/Filters/Filters.js
- src/components/Filters/components/AlphabetFilter.js
- src/components/Sections/Likutim/Main.js
- src/helpers/strings.js
- src/stylesheets/includes/_filters.scss
> AR-828-new

- src/components/Filters/Filters.js
- src/components/Filters/components/AlphabetFilter.js
- src/stylesheets/includes/_filters.scss
likutim alphabet filter mobile display fix
> Alphabet-filter-mobile-fix

- src/redux/modules/my.js
- src/routes.js
- src/sagas/recommended.js
fixed Articles page - it took the wrong route
and more small bugs
> Ar 883 publications fix

- package.json
- public/locales/cs/common.json
- public/locales/de/common.json
- public/locales/en/common.json
- public/locales/es/common.json
- public/locales/he/common.json
- public/locales/it/common.json
- public/locales/ru/common.json
- public/locales/tr/common.json
- public/locales/ua/common.json
- src/components/Pages/PlaylistCollection/widgets/Playlist/Playlist.js
- src/components/Sections/Likutim/Likut.js
- src/components/Sections/Likutim/Main.js
- src/components/Sections/Topics/TopN.js
- src/components/shared/ContentItem/ContentItemContainer.js
- src/components/shared/ContentItem/ListTemplate.js
- src/helpers/utils.js
- yarn.lock
Sort playlist by collection part numbers
espesially for music lists but not only
> Song-numbers

- src/components/FiltersAside/LocationsFilter/CitiesModal.js
- src/components/FiltersAside/LocationsFilter/CountryItem.js
- src/components/FiltersAside/LocationsFilter/Locations.js
- src/components/FiltersAside/TopicsFilter/TagSourceItemModal.js
- src/components/Sections/Events/Holidays.js
- src/components/Sections/Events/UnitItem.js
- src/components/Sections/Lessons/CollectionsModal.js
- src/components/Sections/Programs/CollectionsModal.js
sort places on filter and html bug fixes
> AR-922 sort places 

- src/components/AVPlayer/AVPlayer.js
take played item current time from personal history to sync between devices
> take items current time from my personal history before local storage

- src/components/Pages/PlaylistCollection/widgets/Playlist/Playlist.js
- src/components/Sections/Events/CollectionItem.js
- src/components/Sections/Events/UnitItem.js
- src/components/Sections/Lesson/ItemOfList.js
- src/components/Sections/Lessons/Collectiontem.js
- src/components/Sections/Lessons/DailyLessonItem.js
- src/components/Sections/Lessons/MainPage.js
- src/components/Sections/Lessons/UnitItem.js
- src/components/Sections/Personal/History/Page.js
- src/components/Sections/Program/ItemOfList.js
- src/components/Sections/Programs/ItemOfList.js
- src/components/shared/ContentItem/CardTemplate.js
- src/components/shared/ContentItem/ListTemplate.js
- src/components/shared/ContentItem/helper.js
- src/components/shared/UnitLogoWithDuration.js
- src/redux/modules/filtersAside.js
- src/sagas/lists.js
Added blue progress indication - how much i have watched, on lessons, programs, playlists
> Add progress indication

- src/components/Pages/PlaylistCollection/Container.js
- src/components/Pages/PlaylistCollection/Page.js
- src/components/Sections/Lessons/Collectiontem.js
- src/components/Sections/Lessons/DailyLessonItem.js
- src/components/shared/UnitLogoWithDuration.js
- src/helpers/player.js
start lessons and collections from last watched item
> Show-last-watched

- src/components/Sections/Topics/TopicContainer.js
- src/components/shared/ContentItem/helper.js
fixed children display on search
AR-933
> Topics-children-search-fix

- src/components/shared/ContentItem/helper.js
fully played items to keep indication as fully played but start from the beginning
> start played item from the beginning

- src/components/Filters/components/Date/ButtonDayPicker.js
- src/components/Filters/components/Date/DateFilter.js
- src/components/Filters/components/Date/FastDayPicker.js
- src/components/Filters/components/FlatListFilter.js
- src/components/Filters/components/HierarchicalFilter.js
- src/components/Filters/components/LanguageFilter.js
- src/components/Filters/components/SectionsFilter.js
- src/components/Language/Selector/MenuLanguageSelector.js
- src/components/Sections/Music/Music.js
- src/components/Sections/SimpleMode/Container.js
- src/components/Sections/SimpleMode/Page.js
- src/components/Sections/SimpleMode/SimpleModeList.js
- src/helpers/utils.js
* Use hook `useTranslation` instead of HOC `withTranslation`
* File should have the same name as a component inside it: rename list.js -> SimpleModeList.js
* Added `isToday` helper
* Added `refetch` functionality to `SimpleModeList`
* Supply proper parameters to `WipErr`
* Other minor changes
> Miscellaneous refactors
